$blank$
        <record>
          <cell name="identification-type">$Retailbreak.identification_type$</cell>
          <cell name="customer-code">$Retailbreak.customer_code$</cell>
          <cell name="customer-name">$Retailbreak.customer_name$</cell>
          <cell name="customer-area">$Retailbreak.customer_area$</cell>
          <cell name="region-code">$Retailbreak.region_code$</cell>
          <cell name="break-type">$Retailbreak.break_type$</cell>
          <cell name="break-time">$Retailbreak.break_time$</cell>
        </record>
