<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : retailbreakPersonal.xml
    Created on : 2011年10月20日, 下午1:44
    Author     : Kang.Cunhua
    Description:
        Purpose of the document follows.
-->

<cbrc-ml>
  <gather type="retail-break-personal" name="小贷违约个人客户情况统计表"
    version="$Sendxmlhhcode.version_val$" no="某某统临[2006] 008 号" dept="某某某统计部"
    currency="" currency-unit="">
    <report org="$Sendxmlhhcode.orgcode$" year="$Sendxmlhhcode.year_val$" month="$Sendxmlhhcode.month_val$" fill="$Sendxmlhhcode.fill$"
      phone="$Sendxmlhhcode.phone$" verify="$Sendxmlhhcode.verify$">
      <table type="many" code="retail-break-personal" desc="小贷违约个人客户情况">
$blank$